### ISSUE TITLE
`IvyProcessor` cannot handle version with a patch level number

### ISSUE THREAD

**Issue by sschuberth** [semver4j/semver4j#100]
Adding the following in `IvyProcessorTest` fails:

                arguments("[1.0.0,2.0.0]", ">=1.0.0 <=2.0.0"),
                arguments("[1.0,2.0.0]", ">=1.0.0 <=2.0.0"),
                arguments("[1.0.0,2.0]", ">=1.0.0 <=2.0.0")

This works in https://github.com/vdurmont/semver4j and I believe it should work here, too.

**Comment by piotrooo** [comment]
Fixed in 3.1.0.

**Comment by sschuberth** [comment]
> Fixed in 3.1.0.

Thanks! Was that new version also deployed to Maven central yet? Because I can't find it.

**Comment by piotrooo** [comment]
> Thanks! Was that new version also deployed to Maven central yet? Because I can't find it.

Maven has a little bit of delay with showing current versions.
You can check here that artifact in desired version was published: https://repo1.maven.org/maven2/org/semver4j/semver4j/3.1.0/

You can use it as well.
