### ISSUE TITLE
`RangesList` should have a readable `toString()` representation

### ISSUE THREAD

**Issue by sschuberth** [semver4j/semver4j#101]
The current `RangesList[rangesList=[[>=5.0.0, <8.0.0]]]`-style `toString()` representation is not useful for use in user-facing messages. Instead, `toString()` should return a string like ">=5.0.0 and <8.0.0".

**Comment by piotrooo** [comment]
Sounds interesting. Could you provide a PR with your proposal of this enhancement?

**Comment by sschuberth** [comment]
Sure, I can give it a try. Thanks for your other super-fast fixes, BTW!
