### ISSUE TITLE
Move `RangesListFactory` out of the `internal` package

### ISSUE THREAD

**Issue by sschuberth** [semver4j/semver4j#102]
For use-cases with fixed ranges that are reused as `satisfies()` arguments for different versions, it is necessary to create ranges from strings. IIUC, the only way to do so is via `RangesListFactory.create()`, but I feel bad using an internal class. So please consider making it non-internal.

**Comment by piotrooo** [comment]
It sounds reasonable to me. `RangesListFactory` should be close to `RangesList`.
