### ISSUE TITLE
Reintroduce a `LOOSE` `SemverType` again

### ISSUE THREAD

**Issue by sschuberth** [semver4j/semver4j#107]
In contrast to @vdurmont's [original](https://github.com/vdurmont/semver4j/blob/7653e418d610ffcd2811bcb55fd72d00d420950b/src/main/java/com/vdurmont/semver4j/Semver.java#L643-L647), this library has only `SemverType.STRICT`. Which means there is no elegant way to make

```
RangesListFactory.create("[1.0.0,2.0.0]").isSatisfiedBy(Semver("1.23")) == true
```

if the version string "1.23" is user-provided. However, "1.23" could be trivially fixed to be a Semver by appending ".0" so it reads "1.23.0", and it would be nice if this library could do this internally in a `LOOSE` mode.

**Comment by sschuberth** [comment]
Ah, makes sense. I've already wondered what that function is for 😆 I guess I would have expected a name like "normalize" or so.

As a side question, if you're not planning to introduce other Semver types, should maybe the whole `SemverType` enum be removed?

**Comment by piotrooo** [comment]
Maybe it's a time for this removal and should be done to reduce misunderstandings 🤔

**Comment by sschuberth** [comment]
I agree. Anyway, let me close *this* issue, as it's resolved.
