### ISSUE TITLE
Coercing a Semver should return the original Semver

### ISSUE THREAD

**Issue by sschuberth** [semver4j/semver4j#130]
Currently, `Semver.coerce("3.2.1-rc2")` returns "3.2.1" although I believe it should return "3.2.1-rc2" unmodified. I'm not sure what's the best way to fix this: Either modify `Coerce.coerce` to not strip any valid suffix, or simply let `Semver.coerce` try if `parse` returns `null`, and only if it does call `Coerce.coerce`.

**Comment by sschuberth** [comment]
Implementing it like

    public static Semver coerce(String version) {
        Semver semver = parse(version);
        if (semver != null) return semver;
        String coerce = Coerce.coerce(version);
        return parse(coerce);
    }

uncovered another bug: `Server.parse` treats "v1.2.3" as a Semver, but [it isn't](https://semver.org/#is-v123-a-semantic-version).

**Comment by piotrooo** [comment]
LGTM.

v1.2.3 in the documentation we can read:
> However, prefixing a semantic version with a “v” is a common way (in English) to indicate it is a version number

So parse method should treat this version as a valid, but create a Semver object without v prefix.

**Comment by piotrooo** [comment]
@sschuberth would you prepare an appropriate PR?

**Comment by sschuberth** [comment]
I can do in a few days probably, as I'm on vacation right now.

**Comment by sschuberth** [comment]
Thanks for taking over @piotrooo, this had slipped my mind.

**Comment by piotrooo** [comment]
@sschuberth no worries ;)
