### ISSUE TITLE
XRangeProcessor parses missing patch version as range.

### ISSUE THREAD

**Issue by MarcelBochtler** [semver4j/semver4j#132]
`Semver("2.0.3").satisfies("2.0")` returns `true` due to the XRangeProcessor:

https://github.com/semver4j/semver4j/blob/3a28eb6df364ee292069af31caa8e3a2d5661f67/src/main/java/org/semver4j/internal/range/processor/XRangeProcessor.java#L39-L41

https://github.com/semver4j/semver4j/blob/3a28eb6df364ee292069af31caa8e3a2d5661f67/src/main/java/org/semver4j/internal/range/processor/RangesUtils.java#L18-L20

In this example the patch is `null` and is therefore parsed with the `X_RANGE_MARKER`, resulting in the range `(>=2.0.0 and <2.1.0)`.

Is this the expected behavior?

https://github.com/npm/node-semver#x-ranges-12x-1x-12- doesn't specify this case.

**Comment by piotrooo** [comment]
Here is example:

`1.2` := `1.2.x` := `>=1.2.0 <1.3.0-0`

Your case respectively:

`2.0` := `2.0.x` := `>=2.0.0 <2.1.0-0`

IMHO this works ok.

**Comment by MarcelBochtler** [comment]
Thanks. Missed that from the documentation.
