### ISSUE TITLE
Treat `new Semver("1.0")` as `new Semver("1.0.0")` 

### ISSUE THREAD

**Issue by Fox2Code** [semver4j/semver4j#149]
Programs doesn't always match the `X.Y.Z` versioning format and only do `X.Y`

Treating `X.Y` as `X.Y.0` seems reasonable.

This current lack of support for `X.Y` versioning is probably what causes https://github.com/vdurmont/semver4j/issues/67

**Comment by piotrooo** [comment]
This is on purpose. Look at for the reference issue #107.

**Comment by Fox2Code** [comment]
I think supporting `X.Y` format should be a default because it's currently being heavily relied on in many cases.

**Comment by piotrooo** [comment]
But is not a part of the semver specification. Specyfication clearly says in the [spec-item-2](https://semver.org/#spec-item-2):

> A normal version number MUST take the form X.Y.Z where X, Y, and Z are non-negative integers, and MUST NOT contain leading zeroes. X is the major version, Y is the minor version, and Z is the patch version. Each element MUST increase numerically. For instance: 1.9.0 -> 1.10.0 -> 1.11.0.

For that reason a `coerce` method was introduced - for handle cases similar as yours. But `Semver` object will be follows the semver rules strictly.

**Comment by Fox2Code** [comment]
Well the goal of a library is to assist developers, not follow standard, the reasons why library often follow standard is to better assist developers.

Honestly, what I need is a flexible Semver library that support non standard Semver...

I have an idea, why no making a strictness level, `STRICT`/`SEMI_STRICT`/`COERSE` and default to `SEMI_STRICT`?

**Comment by piotrooo** [comment]
> Well the goal of a library is to assist developers, not follow standard

Nope, you are wrong. The goal of this library is to assist developers by strictly following a standards. That is a reason why the `LOOSE` type was removed.

Of course you can fork this library and add needed enhancements. Feel free.

Btw. I don't get it why you won't to use a `coerce` method...

**Comment by Fox2Code** [comment]
I already use `coerce` method!

Here:
https://github.com/Fox2Code/FoxLoader/blob/af1ddcecdd6811c920177ca56b3207d261cd017c/common/src/main/java/com/fox2code/foxloader/loader/ModLoader.java#L198

**Comment by Fox2Code** [comment]
"Of course you can fork this library and add needed enhancements. Feel free."

If I forked this library it's to contribute too it!

I have an idea what I could change so we are both happy!

**Comment by bric3** [comment]
@piotrooo Is it normal that coerce drops the pre-release info 

```
Semver.coerce("4.2-rc") // 4.2.0
```
