### ISSUE TITLE
Allow SemverException to Extends IllegalArgumentException

### ISSUE THREAD

**Issue by belugabehr** [semver4j/semver4j#166]
We have a validation framework that performs many validations, including a valid SemVer version check.  In general, when invalid data is passed into the framework, it throws `IllegalArgumentException`.  However, some wrapping is needed for this library because it uses its own custom Exception class.  Fine.  But instead, can `SemverException` be updated to extend `IllegalArgumentException` instead of a plain `RuntimeException`?

This more closely aligns with how other string parsing in the JDK is handled:

* https://docs.oracle.com/javase/8/docs/api/java/lang/NumberFormatException.html
* https://docs.oracle.com/javase/8/docs/api/java/util/regex/PatternSyntaxException.html
* https://docs.oracle.com/javase/8/docs/api/java/util/IllegalFormatException.html

**Comment by piotrooo** [comment]
Sounds good to me. If you need this ASAP, please make a PR with changes - I'll merge it and release version. If you can wait give me couple of days.

**Comment by belugabehr** [comment]
Please do note that this change would technically be breaking backwards
compatibility and should be done in a new major version.

If someone had an existing try-catch block, with two code paths, one for
Illegal argument and one for SemverException, this change would change the
executive path.

I'm not sure anyone will care to this level, but something to consider.

**Comment by piotrooo** [comment]
Yes, ideed

**Comment by piotrooo** [comment]
Implemented in 5.0.0
