### ISSUE TITLE
project.version is hardcoded to snapshot version

### ISSUE THREAD

**Issue by harshmadhani** [semver4j/semver4j#173]
I saw the project version set to snapshot even in the tagged checkout.  Whenever I checkout the project to contribute, I have to manually change the project.version to the tag. Any reason for this?

https://github.com/semver4j/semver4j/blob/3ca1a53f4bcee0c0863cee6e9af4632911bafba2/pom.xml#L7

**Comment by piotrooo** [comment]
We change a version in the workflow which is responsible for release an artifact.

https://github.com/semver4j/semver4j/blob/710316cc4a38e43f5ca1bd8e321a670044f30e56/.github/workflows/release.yml#L38

This allows us to not produce additional commit with only changed version.

**Comment by piotrooo** [comment]
I'm closing this issue right now. If you have another question feel free to open this or create new one.
