### ISSUE TITLE
JetBrains Java annotations scope

### ISSUE THREAD

**Issue by charphi** [semver4j/semver4j#180]
The JetBrains Java annotations dependency should have a "provided" scope as specified in its [documentation](https://github.com/JetBrains/java-annotations).

The current scope forces the dependency even if it is not used. In my case, I even have a depedency convergence issue.

**Comment by piotrooo** [comment]
It's true. That was introduced in the last version. Could you make a fast PR with this?

**Comment by piotrooo** [comment]
Fixed in v5.2.1.
