### ISSUE TITLE
Formatter

### ISSUE THREAD

**Issue by xenoterracide** [semver4j/semver4j#217]
So, I'm looking at [Maven's Version Spec](https://cwiki.apache.org/confluence/display/MAVENOLD/Dependency+Mediation+and+Conflict+Resolution#DependencyMediationandConflictResolution-DependencyVersionRanges) and if it's written and I'm understanding it correctly. Build Information has to be `-<build>` instead of `+<build>`. I know this doesn't match the semver spec. It might be nice to be able to specify some kind of Formatter class to allow `getVersion` to print something else. For example

```
new Semver(...).withType(Type.MAVEN)
```

given build information it could use `-` instead, and maybe this could be used in some cases to detect whether a `SNAPSHOT` should be added (although maybe that's too error prone).

note: In my case I've just decided to create a subclass of `Semver` overriding `getVersion` `super.getVersion().replace("+", "-")`

**Comment by piotrooo** [comment]
> [!WARNING]
> The `Semver` object will always follow the [Semver Spec](https://semver.org/) - EOT.

I understand that someone may need to print the version in a different format, so I suggest extending the API in two places:

1. In the `Semver.Builder`

I suggest adding a method `String toVersion(Function<Semver, String> formatter)`. This method would allow returning a customized version string based on the provided function.


2. In the `Semver`

Introduce a method `String format(Function<Semver, String> formatter)` with the same responsibility.

**Comment by xenoterracide** [comment]
I'm going to share a thought I've bee having about my gradle plugin as well as a link into the class where I'm working with semv4j. 

I suspect soon I need to split this class up, perhaps leverage the shallow subclass of MavenSemver that I made in this project.

The thought I've been having is... should `toString()` always return the same as `version()`, my thought is that while a user might want the maven version, it might also be interesting for them to introspect a more detailed version, including the raw semver.

The reason I'm mentioning that here is it might affect design on either my project or yours.

https://github.com/xenoterracide/gradle-semver/blob/6d87851f2ca3faa61cb02e015856072feb2ac19c/src/main/java/com/xenoterracide/gradle/semver/SemverExtension.java#L68
