### ISSUE TITLE
static factory constructor.

### ISSUE THREAD

**Issue by xenoterracide** [semver4j/semver4j#218]
Would be nice to be able to explicitly compose a version

```java
var ver = Semver.coerce("0.1.0"); // really something more convoluted
assertThat(ver).isEqualTo(Semver.of(0,1,0));
```

**Comment by xenoterracide** [comment]
I thought of that, Since they aren't required by the spec, and are inherently stringy by nature I would just use the existing withers. I think, as much as anything I like the more static typed api for certain usages.

```
Semver.of(...).with...("...");
```

**Comment by xenoterracide** [comment]
hmm... not sure how I feel about that solution, it's less stringy, but quite verbose for the basic major.minor.patch scenario. I'll differ, but I think I'd have an `of(int,int,int)` that delegates to what's documented.

**Comment by piotrooo** [comment]
> I'll differ, but I think I'd have an `of(int,int,int)` that delegates to what's documented.

With this builder under the hood, we can easily implement your idea.
