### ISSUE TITLE
io on methods should be consistent

### ISSUE THREAD

**Issue by xenoterracide** [semver4j/semver4j#241]
In relation, but not limited to #216 I have the following code.

```java
        var buildInfo = Splitter.on(GIT_DESCRIBE_DELIMITER).splitToList(
            String.join(GIT_DESCRIBE_DELIMITER, v.getPreRelease())
          );
          return v
            .withClearedPreReleaseAndBuild()
            .withIncPatch()
            .withPreRelease(String.join(SEMVER_DELIMITER, ALPHA, buildInfo.get(0)))
            .withBuild(String.join(SEMVER_DELIMITER, buildInfo));
            
```

This issue is a request to be able to have a consistent set of return/input parameters

I'd like to write this code as something closer to

```java
          return v
            .withClearedPreReleaseAndBuild()
            .withIncPatch()
            .withPreRelease(String.join(SEMVER_DELIMITER, ALPHA, buildInfo.get(0)))
            .withBuild(v.getPreRelease());
```

what this probably means is that there needs to be a version of `withBuild` and `withPreRelease` that takes a `List<String>`.

To be honest, this solution won't actually simplify my case until #216 is fixed, because the parse is wrong, and all of the info is in the first element... so that first `join` isn't really needed... It seems like a reasonable idea though to ask that I could convert the output directly to the input without a further transformation.

**Comment by piotrooo** [comment]
Related with #236
