### ISSUE TITLE
Handle very big number

### ISSUE THREAD

**Issue by piotrooo** [semver4j/semver4j#48]
Right now very big version number eg.:

```
99999999999999999999999.999999999999999999.99999999999999999
```

can easy broke lib, need to be handled.

**Comment by Koziolek** [comment]
Hi, 

I start to play with that enhancement on my fork. If you think about direct usage of `BigInteger` it is not a good idea. That broke API » https://github.com/Koziolek/semver4j/pull/1
I would like to handle this via some „smart shim” on API level but need some more time to do that.

**Comment by piotrooo** [comment]
Hello, 

thanks for this!

`BigInteger` max value looks promising. 
Change methods contract to `String` also will break the API

Maybe in the first implementation just need to handle max integers. Version with max number 2147483647 should be enough :) That need to throw unchecked exception (ie. `IllegalArgumentException` or some custom exception). That allows us to not break an API and easily deliver fixed version of lib.

PS. Remember about using spaces for indentation.

**Comment by Koziolek** [comment]
New PR #74 added. Without API changes.
