### ISSUE TITLE
Setup this repos as a fork of vdurmont/semver4j

### ISSUE THREAD

**Issue by sschuberth** [semver4j/semver4j#56]
This repo does not show up as a fork of [vdurmont/semver4j](https://github.com/vdurmont/semver4j) on GitHub, which makes it hard to [discover](https://github.com/vdurmont/semver4j/network). Any particular reason why this was not set up as a fork? Can you recreate it as a fork?

**Comment by piotrooo** [comment]
Just did it this on this way. Not any particular reason. Let's say I want start from scratch. 
Original repo has 44 forks, so with this number of forks that also could be hard to find.

I won't to recreate it as a fork.
