### ISSUE TITLE
Make `VersionDiff.SUFFIX` consistent with `pre release` name

### ISSUE THREAD

**Issue by piotrooo** [semver4j/semver4j#62]
Right now - after cleanup - we use pre-release name not suffix. Need to be fixed.

**Comment by aartiPl** [comment]
Hi! Thanks for picking up the original project. The library is handy but would be unusable without a maintainer very soon.

Regarding this change, I would reconsider it. It seems that SUFFIX was a perfect name. For example, Kotlin uses a suffix for marking the released versions:
1.7.20-release-201

It is not a pre-release version. It is the official release. From that point of view, the PRE_RELEASE name is incorrect, and SUFFIX was much better.

**Comment by piotrooo** [comment]
Hello,
main goal of this lib is to follow against [semver](https://semver.org/) spec. We want to do this as close as possible to the specification.

Everywhere in the following document, `pre-release` name is used, so using `suffix` is a semver contract-breaker.

I hope you will sill use semver4j lib :sweat_smile:

**Comment by aartiPl** [comment]
Yes, indeed - you are right. I should check the semver docs :-)
Thanks for the explanation - Dzięki! 👍
