### ISSUE TITLE
Hide some classes – replace them by API 

### ISSUE THREAD

**Issue by Koziolek** [semver4j/semver4j#73]
### Enhancement proposal

At this moment, multiple classes from package `org.semver4j.internal` are public and accessible from external places. 
Library should avoid direct usage of those classes and replace some of them by Interfaces. That change makes future breaking-changes easier to introduce. 

Good candidates:
* `StrictParser` – replace by `VersionParser` interface and move `Version` class to package level. 
* `Tokenizers` – internal use only. 
* `org.semver4j.internal.range.processor.XxxxProcessor` – internal use only, but should be registered (somehow) in `RangesListFactory`

**Comment by piotrooo** [comment]
I thought a little bit about your proposal.
The main question which we should answer is - what this changes gives to us? Are we afraid of what changes?

This library is a really small, and if someone want to use `XProcessor` - why not. For `semver4j` I prefer to go for convention over configuration, so if something is in `internal` package, when you use it, you do it for your own risk. I'm afraid that changes unnecessarily complicate simple project.

I fully agree with you that we shouldn't change a public API (I mean classes which aren't in `internal` package).
